### ISSUE TITLE
Pophelp's links rounding shape correction

### ISSUE THREAD

**Issue by cara-tm** [philwareham/textpattern-hive-admin-theme#100]
The rounding shape for "i" ("Help") links isn't perfect.

Actual display (FF PC latest):

![FF PC (latest) display](http://imageshack.com/a/img921/2876/y6CH2f.png "FF PC (latest) display")

Please, try this:

    /* Pophelp round shape correction */
    .pophelp {
	display: inline-block;
	width: 1.538em /* 22 px */;
	padding: 0;
	vertical-align: middle;
	text-align: center;
	line-height: 1.538;
	font-weight: 600;
    }
    
    /* Optional effect */
    .pophelp:hover {
	background: #fff9e1;
	border-color: #ffefae;
	text-decoration: none;
    }

Result:

![Pophelp's links rounding correction](http://imageshack.com/a/img922/7494/b0qERY.png "Pophelp's links rounding correction")

**Comment by cara-tm** [comment]
Circular Smiley!

**Comment by cara-tm** [comment]
Under the `Languages` page, the help rounding shape could be improved a little bit.

Changing the padding property value for the `.thead th a.pophelp` class from 0.4em to 0.6153846153846155em (the half of this element's width) makes the rounding like a circle.

    thead th a.pophelp {
    
        padding: 0 0.6153846153846155em;
    
    }

**Comment by philwareham** [comment]
Improved, cheers. Note that the whole languages panel is being changed at some point in 4.7dev (I don't think pophelp links appear in table headers anywhere else in the system, so I'll remove this whole code).

**Comment by cara-tm** [comment]
Ok. Fine. ;)
