### ISSUE TITLE
Styles for the admin-side preview 

### ISSUE THREAD

**Issue by funtoosh** [philwareham/textpattern-hive-admin-theme#101]
Feature request: add styles for the entry preview in _» Content » Write_ to the submenu in _» Presentation » Styles._ Thus one could easily modify basic styling, such as `font-family` or headline formatting and allow the user to preview in style.

**Comment by philwareham** [comment]
Hi, this is a Textpattern core feature request, not a theme feature. Please open as an issue at https://github.com/textpattern/textpattern/issues instead.

Thanks!

**Comment by funtoosh** [comment]
Ah, yep, of course!
