### ISSUE TITLE
Revisiting issue #99

### ISSUE THREAD

**Issue by phiw13** [philwareham/textpattern-hive-admin-theme#103]
https://github.com/philwareham/textpattern-hive-admin-theme/issues/99

Summary: when clicking the down-arrow on the search widget, the dropdown is misplaced in Firefox running on Windows 10 (the dropdown is offset to the right by about 16px - width of scrollbar).

The issue is only visible when there is little content on the page. If the window shows a scrollbar, the issue goes away.

Minimal test cases:
https://dev.l-c-n.com/txp/_issues/jq-ui-position3.html (widget positioned with `display: flex`)
https://dev.l-c-n.com/txp/_issues/jq-ui-position4.html (widget positioned with `display: grid`)

However:
1. the issue also affects the dropdown of the “List options” with TXP 4.7.
2. the issue can also be reproduced with Chrome and Edge (Win 10 / Linux) - **by clicking more than once on the widget**: click once, position is OK, click a second time to hide the widget, click a third time, position is wrong. Thanks to Firefox developer Daniel H. for alerting me to this.
3. the issue can be reproduced on macOS (Firefox, Chromium) when the system settings are set to show scrollbars **always** (System Preferences > general pane)

@philwareham - if you run macOS 10.12, can you test SafariTP (particularly jq-ui-position4.html)? It possibly is also affected in that case (I run 10.11) – [download here](https://developer.apple.com/safari/technology-preview/) if you need. Otherwise we’ll just wait till Safari 10.1 is released in a week or two.

The root cause of the issue is specifying `body {min-height:100vh;}`. In the [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1329821) I had filed, we concluded that something is “wrong” with the way Jquery computes the positioning.

The only workaround I can think about: instead of `body {min-height:100vh;}`, use the old style hack (will need to double check that IE 11 is not messing up with the `display: flex` on the `<body>`):

```
html { height: 100%; }
body { min-height: 100%; }
```

PS - someone with more energy than me should eventually file a bug against Jquery / Jquery UI. I don’t have the energy to fight with those people. Feel free to use my test cases and reference the Firefox bug.

cc @cara-tm

**Comment by philwareham** [comment]
@phiw13 does this still happen with latest code?

**Comment by phiw13** [comment]
Yes, the issue still exist - but **only** for the search dropdown. The list-options dropdown works fine (and of course, _only_ for short pages, e.g. users panel with only one or two users). Note also: only LTR languages are affected.

This leads to a potential solution. For the `div.txp-list-options` we have these 2 styles:

```
.txp-list-options {
  position: relative;
  float: right;
}
```

This creates a containing block for the dropdown _and_ shrink-wrap it to the width of its content. That is what JQ uses for computing the positioning of the dropdown. For the search widget, JQ uses the viewport as a containing block.

A **possible solution**:

```
.txp-search {
  position: relative; /* containing block */
  float: right; /* shrink-wrap it */
  background: red; /* debug only, so you see the widget width shrink-wrap */
}
```

**Note**:  the `float:right` part should *only* be applied for wide displays, LTR languages (Hive breakpoint > 60em I think). The `position: relative` won’t have any side effects at any width, any device, any LTR or RTL. It might improve performance by some milliseconds.

I’ve tested this on both Windows 10 (Edge, Firefox 57) and macOS (Safari, Firefox 57), both with a short panel and a long panel (24 images uploaded), both with filtered and unfiltered searches.

On macOS, the browsers are only affected if you don’t have overlay scrollbars (System Preferences > General Pane > Show scrollbars always). Or hook up a non-apple, non-touch mouse to your iMac.

**Comment by philwareham** [comment]
Changes committed as suggested. Closing this for now but if issue arises again please reopen. Cheers!
