### ISSUE TITLE
[accessibility] consider adding the aria-current=page attribute for the submenus, indicating the current page

### ISSUE THREAD

**Issue by phiw13** [philwareham/textpattern-hive-admin-theme#118]
https://www.w3.org/TR/wai-aria-1.1/#aria-current

source: https://www.w3.org/WAI/tutorials/menus/structure/

Pseudo diff for hive.php, around line 95:

```
foreach ($tab['items'] as $item) {
  $class = ($item['active']) ? ' class="selected"' : '';
+  $foo = ($item['active']) ? ' aria-current="page"' : '';
  $out[] = '<li'.$class.' role="presentation">'.
-    href($item['label'], array('event' => $item['event']), ' role="menuitem" tabindex="-1"').
+    href($item['label'], array('event' => $item['event']), ' role="menuitem"'.$foo.' tabindex="-1"').
  '</li>';
}
```

The `aria-current=page` is then applied to the currently “active” menu item (`<a>`). You cold even remove the class `.selected` and use the attribute for styling purposes: `.dropdown-menu li.selected` becomes `.dropdown-menu [aria-current]`.

The `$foo` variable deserves a better name…

(at the very least is implemented in Webkit - Safari 10 - https://bugs.webkit.org/show_bug.cgi?id=146012)

**Comment by philwareham** [comment]
Very nice, thanks for the ARIA tip. :)
