### ISSUE TITLE
Edge (win 10) renders the ‘information source’ symbol with an emoji

### ISSUE THREAD

**Issue by phiw13** [philwareham/textpattern-hive-admin-theme#124]
from [changeset](https://github.com/textpattern/textpattern/commit/a2effc23757d9447325029b243222ccdbd20d60f) 

see screenshot below

Firefox uses its default font (Times NR) to render the character. Segue UI (and for MacOS/iOS, SF doesn’t have it either) doesn’t have a glyph to render the character. 

workaround: specify a font-family
 .pophelp { font-family: "Cambria Math", "Apple Symbols"; }
Adjust rest of styles to taste.
Thank you UnicodeChecker for suggesting that "Cambria Math" contains a glyph for that character.

PS - I haven’t tested iOS it is quite possible it uses an emoji as well. The above would fix it. No clue as to what the various Androids do.

![info-edge](https://user-images.githubusercontent.com/8944809/29546518-e172d888-872f-11e7-8166-0e0495a16390.png)

**Comment by philwareham** [comment]
Thanks Philippe, I will improve this in due course.

**Comment by philwareham** [comment]
Please give the latest 4.7dev a spin and see if this issue is improved. Hopefully if we get rid of pophelps mostly from the UI soon this will be obsoleted.

**Comment by cara-tm** [comment]
Yep.
It's perfect, now (tested within Edge latest).

**Comment by philwareham** [comment]
Thanks!

**Comment by cara-tm** [comment]
@philwareham:

I'm working on a project that use such same symbols (https://github.com/cara-tm/modal_box).

The best choice (to cover respectively Edge, Firefox and Safari mobile) is to specify:

`font-family: 'Segoe UI Symbol', 'Cambria Math', 'Apple Symbols'`

<img width="960" alt="emoji" src="https://user-images.githubusercontent.com/61045/29914553-4337a278-8e39-11e7-8fda-f6391689547d.png">
<img width="960" alt="no-emoji" src="https://user-images.githubusercontent.com/61045/29914554-433d54e8-8e39-11e7-9685-224d2d291dd2.png">

**Comment by philwareham** [comment]
Thanks Patrick!

**Comment by cara-tm** [comment]
;)

**Comment by phiw13** [comment]
2 notes

a. technically  you could add `Segoe UI Symbol` to the general font-stack *after* `Segoe UI`, to catch any other special character that might fall back to emojis (e.g. arrow characters, like ▶ (U+25B6)).

b. On iOS 10 here, the  character discussed in this thread (ℹ) is displayed as an emoji - `Apple symbols` is **not** installed on iOS, contrary to what I thought.

- - - - 
Uh, and why does Github think it cleaver to use emoji to display the characters ? hmm - OK they add `Apple Color Emoji` in their general font-stack. From their stylesheet:

```
body {
font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
}
```
