### ISSUE TITLE
Improvement for the drop-down list and line height of its elements.

### ISSUE THREAD

**Issue by cara-tm** [philwareham/textpattern-hive-admin-theme#133]
Textpattern 4.7-dev (latest, synchronisated with Git)

1°. ) From Firefox PC (latest), here is how the drop down is shown:

<img width="959" alt="txp-4 7-dev-list-firefox" src="https://user-images.githubusercontent.com/61045/30475456-31834300-9a07-11e7-83ed-c36270e9b3a3.png">

The line height of the items could be improved a little bit:

    .ui-menu {
       font-size: 13px;
       /* Same line-height as the font-size. 
          The use of unit isn't a best practice (we can choose 1 as a value) */
       line-height: 13px;
    }
    .ui-menu .ui-menu-item {
       /* Corrects the gap between each items of the list */
	margin: -9px 0;
	padding: 9px 0;
    }

Here is the result (FireFox PC (latest) and Chromium PC (latest) respectively):

<img width="960" alt="txp-4 7-dev-firefox-corrected-list" src="https://user-images.githubusercontent.com/61045/30475680-f8aa9514-9a07-11e7-98dc-f466f31165c4.png">

<img width="959" alt="txp-4 7-dev-chromiumpc-corrected-list" src="https://user-images.githubusercontent.com/61045/30475702-083848fa-9a08-11e7-9300-3868e9890bfe.png">

2°. ) The advice into the `custom-example.css` file isn't correct (See: https://github.com/philwareham/textpattern-hive-admin-theme/blob/master/dist/hive/assets/css/custom-example.css#L5)

Correct config is: https://github.com/textpattern/textpattern/blob/dev/textpattern/config-dist.php#L115

**Comment by philwareham** [comment]
Thanks for the report - see related https://github.com/textpattern/textpattern/issues/903 which might have a bearing on this too.

**Comment by cara-tm** [comment]
Don't worry about the entire box position (this has been well diagnosticated by Philippe)

Other screenshots (Edge (latest) and IE 11 respectively):

<img width="958" alt="txp-4 7-dev-edge-corrected-list" src="https://user-images.githubusercontent.com/61045/30483447-3f11dc46-9a27-11e7-8435-b13e802b6c04.png">

<img width="959" alt="txp-4 7-dev-ie11-corrected-list" src="https://user-images.githubusercontent.com/61045/30483452-45a05010-9a27-11e7-9be1-a551cadeadd7.png">

**Comment by philwareham** [comment]
This has been fixed in repo - will be in Textpattern core once issue 903 is resolved.
