### ISSUE TITLE
JQ-UI menu items display large gap in Chromium browsers

### ISSUE THREAD

**Issue by phiw13** [philwareham/textpattern-hive-admin-theme#136]
/* in the category of stupid things encountered on a sunny monday morning */

STR
1. Open Chrome / Opera
2. Navigate to the [design-patterns/jq-ui-menu](http://design-patterns.textpattern.io/docs/#ui-doc-jquery-ui--menu) widget.
3. enjoy the large gap above menu-items that have a submenu

Apparently Chromium browsers think that the `list-style-image` should affect the spacing - but only when there is a sub menu. No don’t ask me why, I haven’t a clue. I suspect yet another bizarre JQ-UI freakiness.

The fix is simple - set the `<li />` to `display: block` (instead of the default `display: list-item`); that will prevent the generation of a list-marker.

```
.ui-menu .ui-menu-item {
  display: block;
}
```

Note: the `list-style-image` hack is still needed for Edge/IE11 - `</bloat>`.

**Comment by philwareham** [comment]
Cheers Philippe, I'll incorporate this change shortly.
