### ISSUE TITLE
Consider suppressing text-decoration for some (RTL) languages

### ISSUE THREAD

**Issue by phiw13** [philwareham/textpattern-hive-admin-theme#147]
In particular, text in languages such as Arabic, Farsi (Persian), Urdu [*] is very hard to read with `text-decoration: underline`.

Most Farsi webpages I‘ve seen suppress it, Wikipedia does it for Arabic, but not Farsi (lack of people to maintain ?).

:lang(ar,fa,ur) a:hover,
:lang(ar,fa,ur) abbr[title] { text-decoration: none; }

On the flip side - it is mainly used for `a:hover` …

[*] those are the only 3 languages affected in Textpattern.

**Comment by phiw13** [comment]
Hold on - the above selector will only work with Safari :-) Other browser still need to catch up on that.

use `[lang|="ar"] a:hover, [lang|="fa"] a:hover, [lang|="ur"] a:hover` instead.

**Comment by philwareham** [comment]
Thanks Philippe, done that in source code. Will be in next build.
