### ISSUE TITLE
Improve CJK font-stack (selectors + macOS/iOS fonts)

### ISSUE THREAD

**Issue by phiw13** [philwareham/textpattern-hive-admin-theme#152]
1/ Chinese
* given your current selectors, your rules are overwritten by the `body` rules
* specify macOS / iOS fonts - some people in Taiwan /HK have mentioned seeing sometimes the ‘wrong’ character (the simplified Chinese one instead of the traditional Chinese one).

```
/* traditional Chinese - Taiwan, Hongkong */
:lang(zh-tw), :lang(zh-hk) {
font-family: "PingFang TC", PMingLiU, sans-serif;
}
/* simplified Chinese - PRC */
:lang(zh-cn) { font-family: "PingFang SC", SimHei, sans-serif; }
```

2/ Japanese.

* The current selector `lang=ja-jp` won’t match on TXP 4.7, the `lang` attribute is now set to `ja` instead.
use `[lang|=ja]` or (better) `:lang(ja)`
* fontstack (optional): add `Hiragino  Sans` - better on iOS, bonus points 9 weights. Meiryo UI matches closer to Segoe UI

```
:lang(ja) {
font-family: "Hiragino  Sans", "Hiragino Kaku Gothic Pro", "Meiryo UI", sans-serif;
font-weight: 300;
}
```

PS - you may want to review your repetitively specifying `font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;`.

Use `font-family: inherit` instead. That way, non-western/roman languages use the correct font.

**Comment by philwareham** [comment]
Cheers. I'm not too clued up on the `:lang()` pseudo element, although [I've read this](https://drafts.csswg.org/selectors-4/#the-lang-pseudo) - does the browser try to auto detect the `lang` if not attribute is found? Should I be using that instead of, for example, `[lang="zh-cn"]`?

**Comment by phiw13** [comment]
No, as far as I can tell no browser will try to auto-detect if no attribute is present. But `lang()` is a more generic selector than `[lang=""]` in a way. The browser will evaluate the document, see the attribute set on the root and then set the font-family (in this case). See it at work in [this test case](https://dev.l-c-n.com/_junk/lang.html) - view source and use the inspector tool to check what is used, and the cascade.

What you presently have in textpattern.css is [lang="zh-cn"] { font-family: xxx } which means use that font-family for elements with that attribute set. Ok, it is applied to the `html` element, and then the stylesheet specifies `body { font-family: yyy }`, thus overriding the previous.

If you prefer attribute selectors, you will need `[lang="zh-tw"] body, [lang="zh-hk"] body {}`. The `:lang()` selector is more concise. Or (fun with selectors !), note the pipe character (see [spec text](https://drafts.csswg.org/selectors-4/#attribute-representation), scroll to examples):

```
/* all Chinese, use traditional Chinese font - Taiwan, Hongkong */
[lang|="zh"] body {
font-family: "PingFang TC", PMingLiU, sans-serif;
}
/* more specific selector for simplified Chinese - PRC */
[lang="zh-cn"] body { font-family: "PingFang SC", SimHei, sans-serif; }
```

I prefer the `:lang()` pseudo-class personally.
