### ISSUE TITLE
RTL layout - jQuery UI progress bar animation runs in the wrong direction

### ISSUE THREAD

**Issue by phiw13** [philwareham/textpattern-hive-admin-theme#153]
It really should run from Right to Left.

```
[dir=RTL] .ui-progressbar-value,
[dir=RTL] progress { animation-direction: reverse; }
```

Added `progress` in case you want to style that - see this [sample page](https://dev.l-c-n.com/form-controls/progress.html).

**Comment by philwareham** [comment]
Thanks! Done this.
