### ISSUE TITLE
search field is too wide for iPhone SE, breaks up in two parts

### ISSUE THREAD

**Issue by phiw13** [philwareham/textpattern-hive-admin-theme#156]
That is in portrait mode (does anyone browse de web in landscape mode?). The issue is easily viewable with Safari’s responsive design mode panel.

Fix: `txp-search-input { max-width: calc(100% - 5.5rem)  } `

![hive-search](https://user-images.githubusercontent.com/8944809/33538294-ca367e6a-d903-11e7-9a19-ec9e55bb23ca.png)

**Comment by philwareham** [comment]
Cheers Philippe. Done that now, and tested.
