### ISSUE TITLE
Tiny CSS Improvments

### ISSUE THREAD

**Issue by cara-tm** [philwareham/textpattern-hive-admin-theme#164]
Here is some little tweaks for the latest Hive theme:

1.° Avoid user mouse selection on the label for the dropdown "List options":

    .txp-list-options > :not(ul) {
    /* Depending how many browsers to target by vendor prefixes */
    	-moz-user-select: -moz-none;
    	-khtml-user-select: none;
    	-webkit-user-select: none;
    	-o-user-select: none;
    	-ms-user-select: none;
    /* Main property */
    	user-select: none
    }

2.° Change the list items within the dropdown "List options" as visual pointer elements and extends the width throught the entire length (entire clickable element):

    .ui-menu .ui-menu-item label {
    	display: block;
    	cursor: pointer
    }

3.° Vertical alignment of the checkboxes in front of the items within the dropdown "List options":

    .txp-dropdown .checkbox {
    	vertical-align: middle
    }

**Comment by philwareham** [comment]
Thanks, will investigate.

**Comment by philwareham** [comment]
Thanks! I've done those apart form checkbox alignment. I'm happy with the current alignment of those.

**Comment by cara-tm** [comment]
@philwareham:
May be on your iMac; but not so accurate in modern browsers on PC.

**Comment by philwareham** [comment]
@cara-tm can you screen grab what you are seeing and post here? Thanks.

**Comment by cara-tm** [comment]
Sure!
Here you are (from the latest dev build with your CSS changes): first without `vertical-align` property; second with `vertical-align: middle`:

<img width="960" alt="ff-latest-pc-without-custom-styles" src="https://user-images.githubusercontent.com/61045/34833439-aed8a544-f6ef-11e7-8e89-e8f3e8c3ab97.png">

<img width="960" alt="ff-latest-pc-with-custom-styles" src="https://user-images.githubusercontent.com/61045/34833461-bec95930-f6ef-11e7-86cc-8f74fda504d5.png">

**Comment by philwareham** [comment]
If I apply that `vertical-align: middle` property all MacOS browsers have their checkboxes shifted out of line worse than what currently shows in Windows Firefox - therefore I'm inclined to leave it as it currently is (the checkboxes aren't wildly out of line in your example).

Checkboxes are notoriously inconsistent across platforms, and short of using a (non-native) replacement UI for them, we are at their mercy.

**Comment by cara-tm** [comment]
Ok.
