### ISSUE TITLE
Add 'system-ui' to the font stack

### ISSUE THREAD

**Issue by phiw13** [philwareham/textpattern-hive-admin-theme#169]
It is the official ([spec](https://drafts.csswg.org/css-fonts-4/#valdef-font-family-system-ui)) name, it is supported by Safari 11 (macOS 10.11+) and Chrome 56+ (current version is 63/64) - [caniuse](https://caniuse.com/#search=system-ui).
You still need to keep the rest of the stack for other browsers and backwards compatibility.

```
font-family: system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica, Arial, sans-serif
```

Depending on your Chrome support matrix, consider dropping that horror that is `BlinkMacSystemFont` (it is only used on macOS).

**Comment by philwareham** [comment]
Nice! Will do, thanks.

**Comment by cara-tm** [comment]
@phiw13 

Philippe,
I noticed some browsers can't interpret the font `-apple-system` from the font stack: the CSS engine parser stops on the first occurence of the dash `-`.

I'm using this instead (within quotes) with better results:
`'-apple-system'`

What do you think about?

**Comment by phiw13** [comment]
@cara-tm 
1. Hmm, which browser(s) might that be? Firefox 3+, Opera 12+, IE 8+ don’t seem to have any problem with it.
2. It is a keyword, not a string, in principle quotes should _not_ be used (same as `sans-serif`, `serif`, `monospace`). That is CSS 2.1 stuff.
3. That said, modern browsers, Firefox 52+ and Safari, do not seem to make it an issue if you add quotes around that keyword, they still use the correct font. So if you want to use quotes there, you can do so.
