### ISSUE TITLE
Safari does not support `touch-action: none`

### ISSUE THREAD

**Issue by phiw13** [philwareham/textpattern-hive-admin-theme#174]
( I suspect that is to deny control-freaks the ability to block zooming by setting `body { touch-action:none }` )

Use `touch-action: manipulation` instead.

Although Apple states that the “dreaded” 300ms thing is disabled when `width=device-width` is set for the viewport meta, it does not apply if the user has zoomed in; see the blog post listed below.

[caniuse](https://caniuse.com/#search=touch-action) || [webkit blog](https://webkit.org/blog/5610/more-responsive-tapping-on-ios/)

**Comment by philwareham** [comment]
Thanks Philippe, good to know.
