### ISSUE TITLE
UI for checkboxes investigation

### ISSUE THREAD

**Issue by cara-tm** [philwareham/textpattern-hive-admin-theme#189]
This is not an issue, rather a visual investigation about UI.

    /*! 
    ======================
    Rules for checkboxes style
    */
    /*! Forms */
    .txp-form-field input[type=checkbox],
    /*! Article list */
    .txp-list input[type=checkbox],
    /*! Crop image */
    .edit-alter-thumbnail input[type=checkbox],
    /*! List tables */
    .txp-listtables input[type=checkbox],
    /*! Categories */
    .txp-layout-4col input[type=checkbox],
    /* Sections panel */
    .txp-form-field-value input[type=radio]
    {
    position: relative;
    width: 1.5em;
    height: 1.5em;
    margin-bottom:-.4em;
    background: #fff;
    border: 1px solid #ccc;
    border-radius: 50%;
    -webkit-appearance: none;
    -moz-appearance: none;
    -ms-appearance: none;
    appearance: none
    }
    /*! Forms */
    .txp-form-field input[type="checkbox"]:checked:before,
    /*! Article list */
    .txp-list input[type="checkbox"]:checked:before,
    /*! Crop image */
    .edit-alter-thumbnail input[type=checkbox]:checked:before,
    /*! Global layout */
    .txp-listtables input[type=checkbox]:checked:before,
    /*! Categories */
    .txp-layout-4col input[type=checkbox]:checked:before,
    /*! Sections panel */
    .txp-form-field-value input[type=radio]:checked:before
    {
    display: block;
    /* Can be an SVG file instead */
    content: '\2714';
    position: absolute;
    top:-.1em;
    left:0
    }

Result sample:
![radio-buttons](https://user-images.githubusercontent.com/61045/38014157-ffee4156-3267-11e8-9f1f-97434cb9d0bb.png)

**Comment by phiw13** [comment]
@cara-tm 

Just FWIW, adjust colors to taste.
https://dev.l-c-n.com/form-controls/radio-checkbox.html

(In use in the Sandspace Theme for TXP admin, if you want to test)

**Comment by philwareham** [comment]
Hi both. The general consensus a while back amongst the dev team I seem to remember was to use browser-native form UI where possible. Although I have pushed back and styled `select` fields as they generally look horrible native.

I'm not adverse to changing checkboxes and radio though (in fact it's already there in the UI, see: http://design-patterns.textpattern.io/docs/#ui-doc-jquery-ui--checkboxradio).

What do you reckon? Shall we give it a try?

**Comment by phiw13** [comment]
JQ-UI radio-checkbox are sloooow, especially when there are many (Preferences panel) + the look is top heavy. It _might_ be OK for one isolated instance, eventually (e.g. an on/of switch).

So for me no thanks.

**Comment by philwareham** [comment]
Sorry, I meant just the checkbox/radio custom icons from that example (without the button element) - not using jQuery UI itself.

**Comment by phiw13** [comment]
You can use mines linked above, and adjust to taste. The code is known to work in IE 11+, Firefox 54+, Chrome and Safari (it is all the stuff with the class`.c`selectors). The source code even has a hack to reset the styling to browser default for Firefox < 54.

And remember Edge recognizes `-webkit-appearance: value`.

**Comment by philwareham** [comment]
OK, leave it with me. Thanks.

**Comment by philwareham** [comment]
I'd be nice to get some consistent styling on the `<input type="file">` fields too. Something along the lines of https://tympanus.net/codrops/2015/09/15/styling-customizing-file-inputs-smart-way/ maybe.

**Comment by phiw13** [comment]
This looks mostly the same between IE11+ and Safari/Chrome, while remaining close enough to platform defaults. The button itself is unstylable in Firefox.
IE 11 + Edge put the button at the end, though.
https://dev.l-c-n.com/form-controls/input-type-file.html

I’m not really a fan of the solution of morphing the whole widget into a single button, like your example. It does save some space though…

**Comment by philwareham** [comment]
OK checkboxes and radios styled up, give the latest dev a whirl and let me know.

The input type file we can look at as a separate issue - if at all. Maybe that can wait for 4.8 to investigate.

**Comment by phiw13** [comment]
> checkboxes and radios styled 

Nice, with one caveat: Firefox older than 54 fails with this, it falls back to old GFX-style widgets (see screenshot from Firefox 52ESR below). Some users (Uli !) of TXP use Firefox 45 ESR.

A solution: reset to default system appearance for those.

```
@supports (unicode-bidi:-moz-isolate) {
[type="checkbox"] { -moz-appearance: checkbox; }
[type="radio"] { -moz-appearance: radio; }
}
```

The prefixed `unicode-bidi:-moz-isolate` was dropped with Firefox 54, at the same time as the ability to fully style radio and checkboxes was introduced. See the [release notes](https://developer.mozilla.org/en-US/Firefox/Releases/54), under CSS and under Removals

<img width="695" alt="fx52-esr" src="https://user-images.githubusercontent.com/8944809/38060955-10ad5980-3328-11e8-9a8d-48729ae0fe55.png">

**Comment by philwareham** [comment]
Ah, OK, I wondered why you had rules targeting Firefox below v54 in your demo. Will amend.

**Comment by philwareham** [comment]
Fixed (and tested) in Firefox ESR v52.

The only browser I can't test in is IE 11. I'll close the issue now but if you spot anything then let me know.

**Comment by phiw13** [comment]
>  I can't test in is IE 11

Open page in Edge, at the far right the menu has an item about ‘Internet Explorer. Click and the page will open in IE11. I don’t trust it 100%, but as don’t have anything else to test it atm. One day I’ll have to set up one of those VM’s from modern.ie in VirtualBox.

I think it works correctly, as is, it ignores everything and just uses the default style (you can't really do much better).

**Comment by philwareham** [comment]
Thanks - I was hoping that was the case. As long as IE 11 works and doesn't look bad, I'm not too fussed about aesthetics in that browser (and we can't style it anyway).

**Comment by cara-tm** [comment]
Phil.

Here is some screenshots from IE11 browser:

![ie11-articles-list](https://user-images.githubusercontent.com/61045/38160798-48762b3e-34c3-11e8-8bf5-3af5d3e8851e.png)
![ie11-section-panel](https://user-images.githubusercontent.com/61045/38160799-48980a88-34c3-11e8-8d2d-83b6e2367ac2.png)

**Comment by philwareham** [comment]
Thanks Patrick - I’m happy with that.

**Comment by phiw13** [comment]
Yeah, you can’t really make it much better. In theory, you can use the `::-ms-check` pseudo-element to modify the look – here is the [documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/%3A%3A-ms-check), but from my testing it is a quite a bit quirky. The elements react to `width`, `height`, `position`, `margin` in the normal way, though.

```
::-ms-check {}
:checked ::-ms-check {}
```
