### ISSUE TITLE
Progress element can be styled in IE 11 and Edge

### ISSUE THREAD

**Issue by phiw13** [philwareham/textpattern-hive-admin-theme#190]
Demo here: https://dev.l-c-n.com/form-controls/progress.html

styles needed (in addition - the demo above has everything commented in the source code)

```
progress { border: 0, color: transparent; }

progress::-ms-fill {
  background-color: /your background color */;
  background-image: /* your gradient */;
  background-size: /* your background size */;
  animation: /* your animation */;
  border: 0;
}
```

Note: animation does not work (Edge 16 and older, IE 11). But then, it does not work in Chrome either (and older versions of Firefox, but I don’t remember which ones, I _think_ < 55).

**Comment by cara-tm** [comment]
In Chrome (PC):
First of the first group works;
First of the second group works;
Two progress bars of the third group work, too.

**Comment by phiw13** [comment]
@cara-tm 
Yeah, I would hope all animation in the first group is working, it is the bloody ugly default appearance.

In the third group the only animation that works is scripted, the CSS animation of the background image fails. I was told that the `@keyframes` must be inserted inside the shadow DOM, but I’ve currently no idea how (I don’t particularly care, I don’t find that animated background-image particularly useful or nice. For my own use, I don’t use it)

**Comment by philwareham** [comment]
OK, leave it with me again. Will add styles.

**Comment by philwareham** [comment]
Done and now in dev. Again I've not checked IE 11 but all other browsers look to be rendering as intended.
