### ISSUE TITLE
design patterns  page (and other docs) need a favicon

### ISSUE THREAD

**Issue by phiw13** [philwareham/textpattern-hive-admin-theme#191]
Every time I look at the Safari Dev tools, the console b*tches about the favicon being 404…

**Comment by philwareham** [comment]
Yeah same here, I nearly added a favicon yesterday but forgot to. Will do it soon.

**Comment by philwareham** [comment]
This should be fixed now.

**Comment by phiw13** [comment]
Yes!
My delicate sense of chaos restored.

Thank you.
