### ISSUE TITLE
Limit the width of input file fields

### ISSUE THREAD

**Issue by philwareham** [philwareham/textpattern-hive-admin-theme#196]
Need to set a max-width so it doesn’t break mobile view.

**Comment by phiw13** [comment]
While you are at it, constrain the categories `select` widget (long long category names, easy to reach in some languages with the larger font-size). While it has a `max-width` set, its parent is currently an inline-block, that will expand to accommodate the contents. Easiest is set

```
@media (max-width:480px) {
.inline-file-uploader-actions { display: block; }
}
```

**Comment by philwareham** [comment]
Thanks - I included that rule too.
