### ISSUE TITLE
± 2px gap correction into input & select fields for better vertical-alignment

### ISSUE THREAD

**Issue by cara-tm** [philwareham/textpattern-hive-admin-theme#198]
.txp-form-field-value input[type="text"],
        .txp-form-field-value select {
            padding-top: 0.2em;
            padding-bottom: .3em;
    }

**Comment by philwareham** [comment]
Hi. Can you give a screengrab of why this is needed?

**Comment by cara-tm** [comment]
Sure.

Here is 2 screen shots (current TXP 4.7 beta 3 from Firefox PC Quantum 59.0.2) with and without rules:

![with-rules](https://user-images.githubusercontent.com/61045/39129258-52fdb870-470a-11e8-9e19-d142b9051074.png)
![without-rules](https://user-images.githubusercontent.com/61045/39129267-5ca6bcaa-470a-11e8-9c80-eef0a05530cc.png)

**Note**: I changed the values (compensated) for a much better rendering as this:

    .txp-form-field-value input[type="text"],
        .txp-form-field-value select {
            padding-top: 0.1em;
            padding-bottom: 0.4em;
    }

**Comment by philwareham** [comment]
Can you show me how that affects Chrome on PC? Doing the padding rules as you've suggested mess up the vertical alignment of Safari, Chrome *and* Firefox on MacOS pretty badly.

Since Chrome PC is the most widely used browser by a long way, we should see how that is affected before deciding making any changes to established rules.

**Comment by phiw13** [comment]
Uh? what did Firefox 59 (Windows) change to the box generation for form controls ?

**Comment by cara-tm** [comment]
Here it is (Google Chromiun PC latest version):

![with-rules](https://user-images.githubusercontent.com/61045/39134720-93351b2e-4717-11e8-8e19-009b7c11ff04.png)
![without-rules](https://user-images.githubusercontent.com/61045/39134728-98a56e74-4717-11e8-9490-1e1d6fcf8b0e.png)

**Comment by philwareham** [comment]
Sorry, I'm going to leave this CSS as it currently is - since it renders correctly in the majority of browsers. Also changing of padding on `select` would also affect buttons and other input fields as they currently are all equal heights (for inline form elements). Thanks anyway.
