### ISSUE TITLE
cursor: text rule on tab links

### ISSUE THREAD

**Issue by cara-tm** [philwareham/textpattern-hive-admin-theme#203]
Is there a good raison why `cursor: text` is applying onto the preferences tab links?

    .ui-tabs .ui-tabs-nav li.ui-state-disabled .ui-tabs-anchor, .ui-tabs .ui-tabs-nav li.ui-tabs-active .ui-tabs-anchor, .ui-tabs .ui-tabs-nav li.ui-tabs-loading .ui-tabs-anchor {
        cursor: text;
    }

This simple change restores a more natural behavior on the anchors list hover states:

    .ui-tabs .ui-tabs-nav li.ui-state-disabled .ui-tabs-anchor, .ui-tabs .ui-tabs-nav li.ui-tabs-loading .ui-tabs-anchor {
        cursor: text;
    }

**Comment by philwareham** [comment]
It seems to be from the default jQuery UI rules - I guess they felt that since you are already viewing the active tab there was no need to indicate it's a link. But I agree we should leave it as the standard browser behaviour here. Done.
