### ISSUE TITLE
Better "search" icon rendering (cross browsers)

### ISSUE THREAD

**Issue by cara-tm** [philwareham/textpattern-hive-admin-theme#207]
I know you will not appreciate what I suggest to you ;)

Here is a solution for the default **Four Point Seven** theme if you envisage a better support for the "search" icon within a large choice of browsers (currently, this icon doesn't appear into some browsers).

First of all, remove the SVG background into the default CSS.

Then, consider this new markup:

    <div class="search" aria-label="<txp:text item="search" />" itemscope itemtype="https://schema.org/WebSite">
    <meta itemprop="url" content="<txp:site_url />">
    <form role="search" method="get" action="<txp:site_url />" itemprop="potentialAction" itemscope itemtype="https://schema.org/SearchAction">
    <meta itemprop="target" content="<txp:site_url />?q={q}">
    <input name="q" type="search" itemprop="query-input" placeholder="<txp:text item="search" />"<txp:if_search> value="<txp:search_term />"</txp:if_search> id="search"><label for="search"><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32"><g fill="#333"><path d="M4,13c0-5,4-9,9-9c5,0,9,4,9,9c0,5-4,9-9,9C8,22,4,18,4,13z M13,19c3.3,0,6-2.7,6-6s-2.7-6-6-6s-6,2.7-6,6S9.7,19,13,19z"></path><path d="M17.5,19l1.5-1.5l4.5,3L28,25c0,0,0,1.5-0.75,2.25S25,28,25,28l-4.5-4.5L17.5,19z"></path></g><foreignObject><span><img src="<txp:site_url />img/magnifier-glass.png" width="24" height="24" alt="<txp:text item="search" />" /></span></foreignObject></svg></label>
    </form>
    </div>

Finally, here is some new rules:

    form[role="search"] {position: relative}

    form[role="search"] label {
    position: absolute;
    top: 3px;
    left: 3px;
    width: 33px; 
    height: 33px;
    cursor: pointer
    }

    /*! For Chromium: needed */
    @supports (display: flex) {

        svg:not(:root) foreignObject {visibility:hidden}

    }

    form[role="search"] svg foreignObject span {
    display: block;
    width: 33px;
    height: 35px;
    vertical-align: middle;
    text-align: center;
    font-size: 1.2em
    }

    form[role="search"] svg foreignObject span img {
    margin-top: -.3em
    }

Here is the PNG version of the icon as a fallback: https://www.flaticon.com/free-icon/magnifier-glass_23759

**Comment by philwareham** [comment]
Hi, this is opened in the wrong repo - can you please copy to https://github.com/textpattern/textpattern-default-theme

Also, which browsers are affected by this? I test in Edge, Safari, Firefox and Chrome and all looks as intended in those here.

**Comment by cara-tm** [comment]
Hi Phil.

Here is some screenshots (no problems within all recent browsers):

<img width="960" alt="chromium" src="https://user-images.githubusercontent.com/61045/40583783-7b4deb1a-6195-11e8-9c3c-1a23698cc23a.png">

<img width="960" alt="better-search" src="https://user-images.githubusercontent.com/61045/40583779-6f0c71a0-6195-11e8-8f59-d0feb1c7c02b.png">

<img width="960" alt="safari" src="https://user-images.githubusercontent.com/61045/40583784-877c68c6-6195-11e8-9cb2-5e7c555fe460.png">

<img width="960" alt="navigator" src="https://user-images.githubusercontent.com/61045/40583786-953d5aba-6195-11e8-9ee8-2a317d4496b1.png">

**Comment by philwareham** [comment]
Eerr, so what's the original issue? The theme repo states our supported browsers:

* Internet Explorer 11.
* Chrome, Edge, Firefox, Safari and Opera the last two recent stable releases.
