### ISSUE TITLE
Log in page

### ISSUE THREAD

**Issue by cara-tm** [philwareham/textpattern-hive-admin-theme#264]
Here is some new styles for the login page within the Hive theme (because I definitely use it for efficient) and some amends for better rendering (see inline comments for more details):

    /* Login page
       =========== */

    /* Shadow arround the form */
    #login_form {
        padding: 2em 6em;
        box-shadow: 0 10px 70px 0 rgba(108, 158, 195, .25)
    }

    /* Center things */
    .login-stay + p,
    .login-forgot,
    .login-view-site {text-align: center}

    /* Push on the right for differenciation */
    .login-stay {
        display: inline-block;
        width: 100%;
        vertical-align: middle;
        text-align: right;
        white-space: nowrap
    }
    /* Vertical alignment for the text based on the checkbox and the icon */
    .login-stay label {vertical-align: text-bottom}

    /* Better hide text: the current méthod show the alternative text on the parent in right alignment */
    .ui-icon-help {
        overflow: hidden;
        text-indent: 100%;
        white-space: nowrap
    }

    /*
     * General: main heading
     */
    /* Current text-indent isn't enough and may show in small screens */
    .login h1, .welcome h1 {text-indent: -200%}

    /* Take advantage of new measures in web design in order to make the logo responsive */
    @media screen and (max-width: 47em) {

        #login_form {padding: 2em 1em}
        .login h1, .welcome h1 {font-size: 5vmin}

    }

Result:
![login](https://user-images.githubusercontent.com/61045/47602257-a4758d80-d9dc-11e8-86fc-986fb2b66822.png)

**Comment by philwareham** [comment]
Done based on issue in Textpattern repo. Closing here.
