### ISSUE TITLE
File input field

### ISSUE THREAD

**Issue by cara-tm** [philwareham/textpattern-hive-admin-theme#273]
(TXP 4.7-dev)
Here is the current presentation of the file input field into the "Image" page as viewed within Firefox PC latest version (see: pic N°1).

Maybe you could try this new rules instead in order to respect your UI (see: pic N°2):

    [type="file"] {
        height: auto;
        min-height: 2.3076923077em;
        padding: .3076923077em;
        border: 1px solid #ccc;
        border-radius: 0;
        background: #fff;
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none
    }

![ff-pc-latest-current-ui](https://user-images.githubusercontent.com/61045/49654182-705ba680-fa37-11e8-9f87-8391b20d62de.png)

![ff-pc-latest-corrected-ui](https://user-images.githubusercontent.com/61045/49654134-4e622400-fa37-11e8-8dee-3330d7b1913e.png)

**Comment by cara-tm** [comment]
Ok. No worries.

**Comment by philwareham** [comment]
Fixed and tested in IE11, Edge, Firefox, Chrome on Windows 10 and Safari, Firefox and Chrome MacOS.

**Comment by cara-tm** [comment]
Here is what you're looking for ;)

![ie11](https://user-images.githubusercontent.com/61045/49941810-dc308a00-fee3-11e8-804a-be4b40cbfa77.png)

![edge](https://user-images.githubusercontent.com/61045/49941827-e5215b80-fee3-11e8-9d20-5be7d3a901e0.png)

**Comment by philwareham** [comment]
Cheers! That's good enough for me.
