### ISSUE TITLE
Hive mock-ups are missing SVG images

### ISSUE THREAD

**Issue by phiw13** [philwareham/textpattern-hive-admin-theme#276]
console reports:

[Error] Refused to load data:image/svg+xml,%3Csvg […] because it does not appear in the img-src directive of the Content Security Policy.

**Comment by petecooper** [comment]
@phiw13 - can you retest, please? I've opened the taps on `img-src` to include `data:` - if this resolves I will roll out to other design patterns sites.

**Comment by phiw13** [comment]
Yes the CSP is the issue; `img-src` need to allow for `data`.

I retested on https://design-patterns.textpattern.com/docs/ and https://design-patterns.textpattern.com/mockups/

No icons are visible (3 devices, Safari / Firefox, clearing caches etc).

PS - there is also a GIF file served as with a `data` URL embedded in the stylesheet - noting this for the sake of completeness.

**Comment by petecooper** [comment]
@phiw13 - thanks for the update. Please try now.

**Comment by phiw13** [comment]
>  Please try now.

Yes ! All icons are showing at https://design-patterns.textpattern.com/docs/#ui-doc-jquery-ui--icons

**Comment by petecooper** [comment]
Bravo. I had got ahead of myself and missed a step in the SVG CSP chain. @philwareham - I think we can close this now, I'll sanity check the SVG CSP (OMG WTF BBQ etc) in companion sites.

**Comment by philwareham** [comment]
Hi. Still seems to be some CSP issues on the [design patterns page](https://design-patterns.textpattern.com/docs/) - I will check what is in your server config and make the necessary amends shortly.

**Comment by petecooper** [comment]
@philwareham - no worries. Not seeing any CSP issues here, so please let me know what URL(s) throw the error(s) and I'll gladly double-check.

**Comment by phiw13** [comment]
> […] some CSP issues […]

Indeed, Safari flags 24 errors for `style-src`. Those were not there last week

**Comment by petecooper** [comment]
>Indeed, Safari flags 24 errors for style-src and script-src. Those were not there last week.

Odd. I haven't touched it since resolving reported issues in https://github.com/textpattern/server-config/commit/4b21eeb871d42e7e00fb9aca3b5f4e8b917a783c - @phiw13: can you list one or more URLs where it's happening, please? Thank you.

**Comment by phiw13** [comment]
@petecooper 

Phil mentions this page: https://design-patterns.textpattern.com/docs/. That is also where I see those 24 errors.

**Comment by petecooper** [comment]
@phiw13 - thank you, I spotted them just before your post. I will address now, thanks for the report!

**Comment by petecooper** [comment]
@phiw13 @philwareham - should now be working, fixed by https://github.com/textpattern/server-config/commit/b64c3d3139c6b07309fe3fcd0d8a15c18a0d2ab4 - please test when you have a moment, thank you.

**Comment by phiw13** [comment]
All gone now.

**Comment by philwareham** [comment]
Yep - all good here now too. Thanks Pete, closing.
