### ISSUE TITLE
When site title is blank, logout button in header moves to opposite side

### ISSUE THREAD

**Issue by petecooper** [philwareham/textpattern-hive-admin-theme#338]
Affects `Four Point Seven` and `Four Point Eight`.

Expected behaviour: when site name is set, logout button is away from the rest of the header content (i.e. in English, header content is left, logout is right).

Unexpected behaviour: when site name is blank, logout button appears after the rest of the header content (i.e. in English, header content is left, logout is after it).

**Four Point Seven - no site title**

![Screen Shot 2019-11-06 at 08 25 05](https://user-images.githubusercontent.com/226578/68281399-7c991b00-006f-11ea-85e1-518457b933c6.png)

**Four Point Eight - no site title**

![Screen Shot 2019-11-06 at 08 25 08](https://user-images.githubusercontent.com/226578/68281472-9d617080-006f-11ea-9cc4-71a403218653.png)

**Comment by philwareham** [comment]
OK, good catch - will fix in due course.

**Comment by philwareham** [comment]
Fixed now, thanks Pete.
