### ISSUE TITLE
Consider setting the Preview dialog to fixed position.

### ISSUE THREAD

**Issue by phiw13** [philwareham/textpattern-hive-admin-theme#351]
The dialog now has a specific class (`.txp-preview-container`) to go along with .ui-dialog. This can be used to set the dialog to `position:fixed` for it to remain pinned when the user scrolls down the page.

**Comment by philwareham** [comment]
OK. We could just apply `position:fixed` to all `.ui-dialog` to be of benefit across all dialog boxes, not just preview. I've just tried it on my test install and it works as expected.

**Comment by phiw13** [comment]
Ahem: https://github.com/philwareham/textpattern-hive-admin-theme/issues/181

**Comment by philwareham** [comment]
Yeah I saw that a hour or so ago! Will revisit tomorrow. Thanks Philippe.

**Comment by phiw13** [comment]
So, hmm, yeah it is a bit of a lovely mess. 

Start with `.ui-dialog { position: absolute; }` and then further in the stylesheet `.txp-preview-container { position: fixed; }` ? Nope the JQ-UI script decides on `position:absolute` in the inline style. Upping the specificity on the selector `.txp-preview-container.ui-dialog` has no effects. The script only listens to the `.ui-dialog` on its own as this works: `#page-article .ui-dialog {}`. (less flexible, plus if someone writes an extension for the Write panel with a similar dialog as the tag builder,…)

Only decent solution: using `!important` as in: `.txp-preview-container { position: fixed; }`

or flipping it around:

```
  /* all */
.ui-dialog { position: fixed; }
  /* override for the tag builder dialog */
.txp-tagbuilder-container { position: absolute !important; }
```

Fun days…

**Comment by philwareham** [comment]
Eurgh, spagetti CSS! OK, hopefully it's done now in Textpattern dev branch. Thanks!
