### ISSUE TITLE
Content overflow at lower end of viewport width

### ISSUE THREAD

**Issue by petecooper** [philwareham/textpattern-hive-admin-theme#363]
4.7.3 handles smaller viewports very well:

![release](https://user-images.githubusercontent.com/226578/73294600-1222f180-41fe-11ea-91f3-c120bc911b6a.png)

There appears to be an overflow issue with 4.8.0 beta.2, example at the same viewport size:

![beta](https://user-images.githubusercontent.com/226578/73294674-2ff05680-41fe-11ea-9a4f-484a959160cd.png)

Note the overflowing content on the right hand side.

See also https://forum.textpattern.com/viewtopic.php?pid=321390#p321390

**Comment by philwareham** [comment]
OK, probably related to the CSS Grid changeover that I've just done in beta 2. Will investigate and fix prior to 4.8 final release. Thanks for the report Pete.

**Comment by phiw13** [comment]
It is interesting that the iOS simulator and the original report in the forum show much less (or none on iOS simulator) that Pete’s screen grab. The Responsive design view on Safari / Firefox and Edge(traitor edition-with-chromium) show no overflow either.

On iOS, the actual content column (`div.txp-layout`) is slightly larger that it should be, right hand visual margin is less than the left hand one. Setting `div.txp-layout { gap: 0; }`*for small screens only* solves that.

<img width="433" alt="hive4 8dev" src="https://user-images.githubusercontent.com/8944809/73317787-a6cb3500-427a-11ea-99f4-03d3d60a62e3.png">

**Comment by philwareham** [comment]
I believe this is now fixed, based on @phiw13 suggestion. If not, please reopen.
