### ISSUE TITLE
Add menu for Textpattern help

### ISSUE THREAD

**Issue by philwareham** [philwareham/textpattern-hive-admin-theme#39]
I quite like the way WordPress handles this, by having a drop down on the WP logo which gives access to:
1. about WP
2. WP website
3. documentation
4. support forums

**Comment by philwareham** [comment]
Will have to be Textpattern 4.7 now, if included at all ;)

**Comment by funtoosh** [comment]
Like the idea though!

**Comment by cara-tm** [comment]
Yep, Phil.
And may be restore the "Go back to website" link from the login page ;)

**Comment by philwareham** [comment]
Out of scope. Closing.
