### ISSUE TITLE
twisties arrows (.txp-details) missing (TXP 4.9-dev)

### ISSUE THREAD

**Issue by phiw13** [philwareham/textpattern-hive-admin-theme#476]
Actual result: no arrows (on strike ?). The computed value for all 4 borders is 0 (zero).

Relevant style (copied verbatim from Firefox dev tools):

```
h3.txp-summary a::after {
    border-bottom: .25em solid transparent;
        border-bottom-width: 0.25em;
    border-left: .25em solid transparent;
        border-left-color: transparent;
        border-left-width: 0.25em;
    border-left-color: var(--clr-text);
    border-right: 0 solid transparent;
        border-right-width: 0px;
    border-top: .25em solid transparent;
        border-top-width: 0.25em;
    border-width: 0;
```

Note the `border-width: 0;` at the end — that does it…

Similarly affected: `.txp-nav > ul > li.open > a.dropdown-toggle::after` (main menu downward pointing arrows) and probably other similar constructs.

**Comment by philwareham** [comment]
This should be fixed in Textpattern 4.9-dev now. Let me know if not. Cheers Philippe.
