### ISSUE TITLE
Link to public website

### ISSUE THREAD

**Issue by cara-tm** [philwareham/textpattern-hive-admin-theme#556]
### Expected behaviour

Perhaps the link to the public website (including the name of the site) would provide an "external link" icon? Functionality is not obvious to everyone, IMHO.

#### Additional information

Framework version: current Hive theme.

**Comment by philwareham** [comment]
I tried just tried adding the external link icon, but it messes with the text truncation on excessively large site names (where ellipsis are required).

Therefore, given the link already has a title attribute that states 'View site', I am not going to implement, sorry.
