### ISSUE TITLE
Sass number precision

### ISSUE THREAD

**Issue by Sacripant** [philwareham/textpattern-hive-admin-theme#66]
Hello,
I looked a bit the code generated by sass, and I am surprised to see very very long numbers. 

`margin: 0 0.30769230769231em 0 0;`
or
`max-width: 20.30769230769231em;`

I think that this level of precision is completely useless and you can set "precision" option to 5 or in your gruntfile for your sass task.
Or better, use css calc().

**Comment by philwareham** [comment]
That is to avoid browser rounding errors. Google Chrome supports 7 decimal points, and although these are slightly longer, I will leave it as-is thanks.
