### ISSUE TITLE
Patch for display:none instead of visibility on Plugin Options

### ISSUE THREAD

**Issue by Bloke** [philwareham/textpattern-hive-admin-theme#669]
Diff attached (I'm unable to commit to this repo and I haven't cloned it to make a PR). See https://forum.textpattern.com/viewtopic.php?pid=334819#p334819

[display-vis-plugin-opts-diff.txt](https://github.com/philwareham/textpattern-hive-admin-theme/files/10865615/display-vis-plugin-opts-diff.txt)

**Comment by philwareham** [comment]
I think I have fixed this now - committed to main dev bulld. Please verify and reopen if still not fixed in a satisfactory way.
