### ISSUE TITLE
Patch for inline checkbox/radio sets

### ISSUE THREAD

**Issue by Bloke** [philwareham/textpattern-hive-admin-theme#683]
New class introduced `txp-form-field-set` which is used for grouping elements inline. Primarily of use in the UI library for ensuring inputs and their corresponding labels (checkboxes, radios, etc) don't become separated.

Patch is:

```
--- a/src/assets/sass/modules/_layout-specific.scss
+++ b/src/assets/sass/modules/_layout-specific.scss
@@ -342,6 +342,10 @@ body.darkmode.login {
     height: 64vh;
 }
 
+.txp-form-field-set {
+    display:inline-block;
+}
+
 
 /* Presentation -> Forms panel - additional layout
```

I'm unable to comit to this repo so the changes have been made to core directly. If the class name or approach needs revising (perhaps we already have a rule that can cover this), that's cool. The UI\CheckboxSet and UI\RadioSet class constructors will just need tweaking accordingly.

Corresponding discussion thread: https://forum.textpattern.com/viewtopic.php?pid=335227#p335227

**Comment by phiw13** [comment]
To match the spacing between 2 radio-buttons / checkboxes + label combo,  consider adding also 

```
.txp-form-field-set:not(:last-child) { margin-inline-end: .5em; }
```

matching `[type=radio]:not(.ui-checkboxradio)+label:not(.ui-controlgroup-item)`.

See for example on the Preferences Panel > Site , the difference between the two ”Daylight Saving Time” radio groups (the second one uses the `.txp-form-field-set` pattern).

**Comment by philwareham** [comment]
This should now be fixed in the main Textpattern dev build. Please verify and reopen the issue again if not fixed. Ta.
