### ISSUE TITLE
Label alignment of upcoming multiple selects

### ISSUE THREAD

**Issue by NicolasGraph** [philwareham/textpattern-hive-admin-theme#70]
Hi Phil,
[multiple selects support](https://github.com/textpattern/textpattern/commit/da34479da06249287ae175ebc54cb63bfde77ef1) is going to be added into the core. It works well for plugin prefs for example, but I think that it will need some css adjustement because the `div` which wrap the label of the pref uses `align-items: baseline` for now and displays it at the bottom of the row. It would be more user friendly to see it at the top, wouldn't it?

**Comment by philwareham** [comment]
Need to investigate for v4.7.
