### ISSUE TITLE
:user-invalid and :out-of-range pseudo-classes

### ISSUE THREAD

**Issue by phiw13** [philwareham/textpattern-hive-admin-theme#725]
Consider adding support for `:user-invalid` and `:out-of-range` pseudo-classes. Both provide immediate (visual feedback to the user in case of erroneous input

`:out-of-range` is supported by all browsers and applies to fields  such as `input type=number`. The `:user-invalid` is supported by Firefox and Safari (16.5+) and applies to all fields with some validation/input contrains (e.g. date & time input fields in Textpattern); Chromium browsers will possibly support it by the end of the year (2023) (? says caniuse).

Possible styling: same as the error/danger alert boxes

**Comment by philwareham** [comment]
Done, thanks!
