### ISSUE TITLE
replace js snippet that centres the alert box (mesaagepane) with CSS

### ISSUE THREAD

**Issue by phiw13** [philwareham/textpattern-hive-admin-theme#75]
That would make it easier for third party themes to piggy back on Hive theme (along the lines of wet_hive) and allow those themes more flexibility to place the messagepane where they want. Additional benefits: better performance (CCS code execution is faster), less code (39 characters instead of 281 characters…)

remove the following js snippet from hive.php (line 193 at time of writing)

```
$(window).resize(function ()
                    {
                        $("#messagepane").css({
                            left: ($(window).width() - $("#messagepane").outerWidth()) / 2
                        });
                    });
                    $(window).resize();
```

append to `#messagepane` in textpattern.css:

```
left: 50%;
transform: translateX(-50%);
```

add `-webkit-transform: translateX(-50%);` if you still support Safari 8 /OS X 10.8.

**Comment by philwareham** [comment]
OK, will do, thanks!

**Comment by phiw13** [comment]
Thanks!
