### ISSUE TITLE
[RTL] unnecessary padding-right on ul.switcher-list

### ISSUE THREAD

**Issue by phiw13** [philwareham/textpattern-hive-admin-theme#76]
(going through the low hanging fruit…)

```
.switcher-list {
margin: 0 -1em;
padding-left: 0;
}
```

right hand padding comes from `[dir=rtl] ul {padding: 0 2em 0 0}` (specificity…)

fix: `.switcher-list, [dir=rtl] .switcher-list { padding: 0 }` (need to double-check if it doesn’t mess-up anything with the list on the pref panel due to specificity)

yeah, my kingdom for padding-inline-start/end… and friends

screenshot
![switcher-list](https://cloud.githubusercontent.com/assets/8944809/16110770/636aa036-33ea-11e6-8d87-708453ffce46.png)

**Comment by philwareham** [comment]
Padding has been fixed. The alignment of destroy/switcher-action elements could do with flipping to the left side too, so still need to keep this issue open whilst I do that.
