### ISSUE TITLE
Consider rebuilding the header using flexbox for layout 

### ISSUE THREAD

**Issue by phiw13** [philwareham/textpattern-hive-admin-theme#78]
Quoting [my self](http://forum.textpattern.com/viewtopic.php?pid=300369#p300369)
I’m a bit sad that the text string for that link has been replaced by a generic “view site” instead of the title of the website managed by this instance of TXP. That string was the only indication which site is affected by this TXP in this browser tab …

Rebuilding `txp-header` using a flexbox driven layout would avoid the [issue](https://github.com/textpattern/textpattern/issues/719) that lead to that change.

With flexbox layout, you can keep the full title of the site as “view site” text (with overflow hidden etc for very long site names)

See, for example how Sandspace theme handles this: http://dev.l-c-n.com/txp/txp-sandspace-short.html

Some basic rules:

```
.txp-header { display: flex; }

.txp-header h1, .txp-logout { flex: none; }

.txp-logout { margin-left: auto; }

/* but only when the nav is displayed horizontally */
@media (min-width:xxx) { /* insert breakpoint here */
.txp-nav { display: flex; }
}

/* keep same direction for RTL languages
 * - tabbing order still works correctly
*/

[dir=rtl] .txp-header,
[dir=rtl] .txp-nav > ul { flex-direction: row-reverse; }
```

for an example of a page in a RTL language, see http://dev.l-c-n.com/txp/txp-content-write-html-RTL.html

Probably something for a future TXP 4.7 though

**Comment by philwareham** [comment]
Ok sounds good, I will investigate using this and also reinstating the site name on larger page widths. Give me s couple of days.

**Comment by phiw13** [comment]
Would be lovely if you managed to get it in 4.6. Shout (but softly!) if you have problems or questions.

**Comment by philwareham** [comment]
Think this is done now. I think I will also attempt to flow the header in reverse for RTL languages but I'll open a new issue for that.
