### ISSUE TITLE
some minor issues with IE 11 + Edge (14)

### ISSUE THREAD

**Issue by phiw13** [philwareham/textpattern-hive-admin-theme#86]
**[1] submenu on the jq-ui menu display a list marker**
Affected: both IE 11 and Edge latest

Turns out it is a known bug, see ticket #8844
https://bugs.jqueryui.com/ticket/8844

```
.ui-menu .ui-menu-item { 
  list-style-image: url("data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7");
}
```

**[2] IE 11: icon on `select` widget is missing**

(works fine in Edge latest)

IE 11 ignores the embedded data url, it needs to be base64 encoded.

This should do:

```
data:image/svg+xml;charset=utf-8;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIHdpZHRoPScxM3B4JyBoZWlnaHQ9JzRweCcgdmlld0JveD0nMCAwIDEzIDQnPjxwb2x5Z29uIGZpbGw9JyMzMzMnIHBvaW50cz0nMy41LDQgMCwwIDcsMCcvPjwvc3ZnPg==
```

(generated at: http://dopiaza.org/tools/datauri/index.php)

**Comment by philwareham** [comment]
Wouldn't using this rule fix IE11/Edge?

    list-style-image: none;

Or do we have to use the transparent image approach?

**Comment by phiw13** [comment]
No, it has to be that (silly) 1px transparent image. I’ve tried all possible combinations of list-style-* syntax, both on the `UL` and the `LI` to no avail. Thing (and that is with the latest Edge) won’t listen.

**Comment by philwareham** [comment]
Thanks Philippe, will roll into the Textpattern core for testing.
