### ISSUE TITLE
(flexbox layout) Plugin panel layout issue (missing an .txp-layout-1col wrapper)

### ISSUE THREAD

**Issue by phiw13** [philwareham/textpattern-hive-admin-theme#89]
(problem might be an oversight more than anything)

The current mockup only wraps the `h1` inside a `.txp-layout-1col`. The rest of the elements are direct children of the `.txp-layout` block.

As seen on http://design-patterns.textpattern.io/mockups/admin-plugin.html

There are a couple of issues with this.

1. this throws the margins with my Sandspace theme out of whack – world is doomed!… :-( [1]
2. More importantly, the two elements (the `table` container/form and the plugin upload widget (`.txp-control-panel`) now become flex-items which in turn can then cause layout issues. E.g if you open the browser window larger enough, you’ll notice the table doesn’t stretch the full width. Or make he window narrow enough (without triggering the small screen MQ), the table will overflow the window in Firefox + Edge.
3. consistency with other listings panels…

I guess the main point here is the need to have (always) the column-wrappers available, in order for the components inside to layout correctly (and that makes it easier for plugin authors to add their additional components).

Suggested markup

```
<div class="txp-layout-1col">
  <h1>
</div>
<div class="txp-layout-1col">
  <div class="txp-control-panel">plugin upload widget</div>
  <form class="multi_edit_form"><div class="">table etc</div></form>
</div>

```

PS - other than that issue, everything seems to behave as expected (Safari 9 + 9TP, Firefox, Edge, IE 11, Opera + iPod MobileSafari).

[1] http://dev.l-c-n.com/txp/txp-admin-plugin.html

**Comment by philwareham** [comment]
Thanks, this was an oversight  should have been there all along.
