### ISSUE TITLE
Content a.switcher before code in smallest breakpoint

### ISSUE THREAD

**Issue by philwareham** [philwareham/textpattern-hive-admin-theme#91]
For consistency with prefs pane and better ux we should be able to flexbox the content switchers on pages, forms and styles panels to appear before the coding textarea.

**Comment by phiw13** [comment]
I suppose you are aware of the accessibility issues that this *may* rise…

See [this note: 5.4.1. Reordering and Accessibility](https://drafts.csswg.org/css-flexbox/#order-accessibility) in the flexbox spec.

But this question has me wondering: on the 3 affected panels, the ‘navigation’ (the content switchers) comes after the main content box in the DOM. However, when you access those panels, you are not necessarily wanting to access the default one, but want e.g. to access another form-template or page-template. For keyboard users (and to a lesser extend screen readers, as they can more easily navigate the page based on headings) this implies tabbing through the input fields to switch the view to another template.

Wouldn’t it be more logical to have the sidebar be first in the DOM? For larger displays (2 column view), this could be visually displayed as sidebar-on-the-right as it presently is (using the `order` property) without negative effect for accessibility.

The only issue is the location of the “Save” button, which is the very first element in the side-column (that issue already exists on the prefs panel).

**Comment by philwareham** [comment]
I gues we could simply move the content switchers to before the form fields in DOM and have on left side just like on prefs. As for save button, I can put somewhere else but what do you suggest?

**Comment by phiw13** [comment]
Here is a dummy I had coded up earlier today (stylesheet is Sandspaces, that is what I have open in the code editor…). Some notes in the page.

http://dev.l-c-n.com/txp/txp-presentation-pages-T.html

I put the “save” button to the top, because I can - hmm and people in the forum seem to like that, but it is tricky to implement… Personally I’d be fine with leaving it at the bottom of the form.

Tag builder ( I just saw your forum post…) should go after everything else…  Layouting that is a problem for another day… Perhaps some chaos grid like I do here for iPad sized displays (<900px):
http://dev.l-c-n.com/txp/txp-presentation-forms.html

**Comment by philwareham** [comment]
@phiw13 I've just sent @bloke a message about the tag builder and implementing via a jQuery UI dialog window, we'll see what we can do. As far this issue, I'm fairly happy with latest couple of commits so will close and implement in the core shortly.

**Comment by phiw13** [comment]
What you have now is mostly fine, with one issue in 2 column view: if you have lots of pages / forms, the “save” button tends to disappear below the bottom of the window, unless you have a very big / tall monitor.

**Comment by phiw13** [comment]
There is actually another issue with the location of the “Save” button.

In current core and Beta 2, it follows the textareas directly (both in the code/DOM as in the tab chain). Set focus in the textarea, press tab, focus is set on the “Save” button. With your new mockups, there is no such direct link. Keyboard users (and that includes people who usually use a mouse but have the habit of tabbing from form control to form control) will have quite a bit work to save the form / to reach the button.

The textarea(s) are now the last focusable thing on the page basically, so the next tab will go to either the location bar or next link (footer), etc etc. Many tab tab tabs before you reach the save button.

[On OS X, how much work that is depends on your FKA settings  in System Preferences > Keyboard > Shortcuts (at the bottom). Firefox, Chrome, Opera all respect that. Safari has an additional option in its own Preferences (Advanced). No such choices on Windows / Linux, afaik - it is all links + form controls all the time]

The prefs panel is slightly (OK more than slightly) better in this as it contains mostly single line inputs, selects or radios / checkboxes. Focus any one of such controls, edit, then press return / enter, the form will be saved. No such luck with textareas.

I guess AT users will have similar issues.

And yeah, tab chain issues are one of the more complicated and messy issues in UI development…

**Comment by philwareham** [comment]
All true. Logically the save button should be at the end of the flow. I had refrained from that for consistency with the other panels. Let me think about it for a day and make a decision. Cheers.
