### ISSUE TITLE
Feature request: use system fonts as default

### ISSUE THREAD

**Issue by funtoosh** [philwareham/textpattern-hive-admin-theme#96]
Ah, just a feature request/idea, I quite like the idea of using system fonts for CMs's, as used by Bootstrap4, Medium, and (I think) Wordpress, like this:
`font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif;`
There should not be too much alignment problems etc as all these fonts should behave somewhat similar to Arial/Helvetica.

Cheers!
-martin

**Comment by philwareham** [comment]
Hi,

This [has already been done](https://github.com/philwareham/textpattern-hive-admin-theme/commit/574dd186a18104615dd8eec1286d7bf8e3602325) a couple of weeks back :)

You can test it in Textpattern 4.7dev,

**Comment by funtoosh** [comment]
Ups! Didn't look at the dev branch, sorry.
Great it's already in there, the interface _still_ keeps getting better & better.

-m

**Comment by philwareham** [comment]
You can use the current `dist`directory themes from here in a 4.6.x build and they will work fine (as the 4.7 codebase hasn't yet deviated much from 4.6) if you want to use these on a production site.

**Comment by funtoosh** [comment]
Ah, hadn't thought about that, that's pretty easy, good idea!
