### ISSUE TITLE
Progress meter image not really needed

### ISSUE THREAD

**Issue by philwareham** [philwareham/textpattern-hive-admin-theme#97]
We can save a few kilobytes and a couple of HTTP requests by replacing the jQuery UI progress meter images with pure CSS solution instead.

**Comment by philwareham** [comment]
Done. Kind of.

**Comment by phiw13** [comment]
If you are into byte saving… use a background gradient and animate the background-position. The whole thing weights less than 0.5kb on my side. Not need to worry about @2x images. Your @1x image is 0.891kb.

Couple of examples: https://dev.l-c-n.com/_temp/spinner.html

The one thing to remember, the background-position **must** be a multiple of the background-size. In the examples, `background-size: 24px 24px;`, in the animation, `background-position: 48px 0;`

**Comment by philwareham** [comment]
Brilliant, I was looking for a solution like this (the CSS Tricks one I tried yesterday was rubbish, so I dumped it).
