### ISSUE TITLE
Some things

### ISSUE THREAD

**Issue by cara-tm** [philwareham/textpattern-hive-admin-theme#98]
3 little CSS comments for the "Hive" & "Hive Neutral" Themes (4.7.0-dev version):

1.° Vertically align "select" field with others input fields (see how it renders into the "Forms" page):

    .txp-form-field {
            margin: 1em 0;
    /* new property */
    vertical-align: top;
    }

2.° Add white space arround content into select lists to show part of characters below the base line (i.e. "g" letters):

    select {
    /* new property */
    padding-top: 0.155em;
    
        padding-right:1.30769230769231em;
        background:url(...)
    }

3.° With your new very subtile effect around the fixed select list at the bottom of the pages, why do not change the black shadow below the header by a white one (this is just a visual choice)?

    .txp-header {
    box-shadow: 0 1em 1em #fff;
    }

**Comment by philwareham** [comment]
What browser are you viewing in, and can you provide screengrabs for issues 1 and 2? It works fine for me in Webkit browsers and Firefox on Mac.

Issue 3 I'm happy with the dark shadow on fixed header as-is. The sticky list footer (and planned sticky save button on Write page) I haven't fully decided in the styling for yet.

**Comment by cara-tm** [comment]
All modern browsers on PC. Didn't open my iMac. I'm going to make a test.

**Comment by philwareham** [comment]
Can you screengrab for me? And is it 4.7dev or 4.6 you are using? If 4.7 it might be the new system font we are using for PC.

**Comment by cara-tm** [comment]
Yep. 4.7.0. I'll make screen shots for you tomorow.

**Comment by cara-tm** [comment]
Before changes the fields are not horizontally aligned and the "g" letter isn't completely visible within it base line:

![Before changes: FireFox 50.2 PC](http://imagizer.imageshack.us/a/img924/2365/vxjyUF.png "Before changes: FireFox 50.2 PC")

Applying changes, results are better on:

1.° FireFox 50.2 PC:

![Changes on FireFox 50.2 PC](http://imageshack.com/a/img922/3854/wot5Id.png "Changes on FireFox 50.2 PC")

2.° Opera 41 PC:

![Changes on Opera 41 PC](http://imageshack.com/a/img923/4386/FfvwFB.png "Changes on Opera 41 PC")

3.° Microsoft Edge latest:

![Changes on Edge latest](http://imageshack.com/a/img924/6905/6stj4B.png "Changes on Edge latest")


Changes don't affect the display in Mac browsers (webkit & Gecko engines):

4.° Safari 9 Mac:

![Changes on Safari 9 Mac](http://imageshack.com/a/img924/9269/viJdVC.png "Changes on Safari 9 Mac")

5.° FireFox 44 Mac:

![Changes on FireFox 44 Mac](http://imageshack.com/a/img924/820/QamACC.png "Changes on FireFox 44 Mac")

**Comment by phiw13** [comment]
I only see the clipping of descenders in `<select>` widgets with Firefox latest release build; the vertical alignment issue is also only visible with Firefox. Edge has absolutely no problems. Both issues have the same reason: the internal construct of that widget. The computed line-height is 19px for `<select>` widgets, vs 18px for all other widgets (nothing you can do about, afaik). Firefox also has an internal border + padding. That particular issue will probably disappear when Firefox 53 is released - ~June 2017 (that is [bug #140562](https://bugzilla.mozilla.org/show_bug.cgi?id=140562)). Currently known as “nightly” … I haven’t tested yet.

You can minimise the issue of descenders being clipped by removing the `height` you set on all form controls. The `<select>` will still be taller (3px) than the other form controls; the code below works around that (it is *not* perfect, there is still 1px difference in height between `<select>` and other form controls).

```
input::-moz-focus-inner,
button::-moz-focus-inner,
select::-moz-focus-inner {
	border: 0;
	padding: 0;
	outline: none;
}
select:-moz-focusring {
	color: transparent; text-shadow: 0 0 0 #000;
}
```

And then do your own thing to indicate the focus state - which you already, of course.

**Comment by cara-tm** [comment]
@phiw13: Right. Edge (latest) isn't affected. Neither Opera browser all latest versions ("Classic", Developer & Beta Next).

Here is your CSS results with FireFox 50.0.2 (latest) on Windows 10 (latest):

![New rules tests in FireFox 50.02 PC Windows 10 latest](http://imageshack.com/a/img921/8150/IhVdNb.png "New rules tests in FireFox 50.02 PC Windows 10 latest")

**Comment by phiw13** [comment]
Yeah, the descenders (g)  are still clipped by the @height@ specified for all form controls

**Comment by cara-tm** [comment]
My changes on FireFox Nightly Build 53.0.1a (latest version available) PC (Windows 10 latest):

![FireFox Nightly Build 53.0.1a PC Windows 10 latest](https://github.com/philwareham/textpattern-hive-admin-theme/issues/98#issuecomment-266672644 "FireFox Nightly Build 53.0.1a PC Windows 10 latest")

**Comment by philwareham** [comment]
If this is a bug pertaining to Firefox, and is logged already, then I'm inclined to leave things as they are. I'd rather keep the sizing of form elements consistent across browsers. Unless of course you can provide code example of how this can be done.

**Comment by phiw13** [comment]
One way to solve the main issue (clipping of descenders for Roman languages, mostly visible with Firefox / windows but *could* affect other languages - CJK, Indian languages on various platforms):

Given the knowledge that the computed line-height for the select widget on Windows is 19px [*]: make the `height` of  the widget(s) taller! 

Currently, it is set to `2.15384615384615em;` (line 1100 of the unminified hive/textpattern.css), that computes to 28px (18px line-height + 2x 4px padding + 2x1px border).

To please everybody, increase the height to 30px instead. A nice round/even number, plays well with snapping-to-pixel-grid. That should cover most languages across platforms. Might even fix the issue pat was flagging. Please test.

[*] That is, for Roman languages; the `normal` value for `Segoe UI` is about 1.4. I think MS does the same for the Japanese font (Meiryo UI) as Apple does for the Hiragino fonts: constrain the line-height to match the roman fonts when used at system level (UI). If you want a longer explanation on how the `normal` (intrinsic) line-height works across languages, I have a text on that subject somewhere. It is late here, and I have a very good record to listen to…

**Comment by philwareham** [comment]
Hi both. Can you test latest 4.7-dev and let me know if fixed (in Hive theme) as I've put a tentative fix for this in there. Line-height is now 20px so with padding and border form elements are 30px heigh.

Also let me know if Classic is affected and I'll do the same type of amends there,

**Comment by phiw13** [comment]
Looks good to me.

screengrab, Fx 50
![win10-fx50-widgets1](https://cloud.githubusercontent.com/assets/8944809/21168467/8d8d477e-c1f7-11e6-9cd0-6c98daf9f1bd.png)

**Comment by philwareham** [comment]
Great, thanks for the help again Philippe. Closing this.

**Comment by cara-tm** [comment]
Yes guys: it's much better!

But that don't solve the vertical alignment problem with FireFox...
I gave you the solution without affected all other browsers (see my first post with `vertical-align:top` which means: put all elements and its childs on a same line, at the top) but for some reason I don't know, you do not want to apply it.

**Comment by philwareham** [comment]
@cara-tm Can you gran the latest build in the `dist` of this repo, and test the vertical alignment in Firefox PC. My Mac Firefox doesn't have the initial problem so I can't check it.

**Comment by cara-tm** [comment]
@Phil. I think I send you all the screen captures for all the browsers tested (read my previous posts above).

**Comment by philwareham** [comment]
Yes and I've put your vertical align rule in - but you need to test it as I can't.

**Comment by cara-tm** [comment]
Sure!

Here is the new rule test with full successful display (without the 2 pixels gap):

![FireFox PC 50.02 (Win 10 latest) with new rule test](http://imageshack.com/a/img924/5853/iTGxDO.png "FireFox PC 50.02 (Win 10 latest) with new rule test")

**Comment by philwareham** [comment]
OK, try the latest 4.7-dev and let me know.

**Comment by cara-tm** [comment]
Only one word: Perfect!
;)

**Comment by philwareham** [comment]
Yay!
